---
env:
  contexts:
    - name: Default Context
      includePaths: [URL]
      authentication:
        verification:
          method: response
          pollFrequency: 60
          pollUnits: requests
          pollUrl: ''
          pollPostData: ''
      sessionManagement:
        method: cookie
      technology: {}
      structure: {}
  parameters: {}
jobs:
  - type: passiveScan-config
    parameters: {}
  - type: spider
    parameters: {}
    tests:
      - name: At least 100 URLs found
        type: stats
        onFail: INFO
        statistic: automation.spider.urls.added
        operator: '>='
        value: 100
  - type: spiderAjax
    parameters: {}
    tests:
      - name: At least 100 URLs found
        type: stats
        onFail: INFO
        statistic: spiderAjax.urls.added
        operator: '>='
        value: 100
  - type: passiveScan-wait
    parameters: {}
  - type: report
    parameters:
      template: risk-confidence-html
      reportTitle: ZAP by Checkmarx Scanning Report
      reportDescription: ''
